version: "3.7"

services:
  
  mongodb:
    image: mongo:4.2.13-bionic
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  flask:
    build: ./api
    container_name: flask
    restart: always
    environment:
      - APP_NAME=app
    expose:
      - 8080
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  react:
    build: ./frontend
    container_name: react
    restart: always
    networks: 
      - frontend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks: 
      - frontend

networks: 
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local