version: "3.7"

services:

  flask:
    build: ./api
    container_name: flask
    restart: always
    environment:
      - APP_NAME=app
    expose:
      - 8080

  react:
    build: ./frontend
    container_name: react
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"