---
- name: Create MongoDb Container
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Pull mongo image
      docker_container:
        name: mongodb
        image: mongo:4.2.13-bionic
        state: started
        restart: yes
        restart_policy : on-failure
        exposed_ports:
          - "27017"
        env: 
          MONGO_INITDB_DATABASE: "flaskdb"
          MONGODB_DATA_DIR: /data/db
        volumes:
          - mongodbdata:/data/db

- name: Pull and Run Custom Flask image
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Pull flask image
      docker_image:
        name: hargovind04/checkup_ease_backend:latest
        source: pull

    - name: Running flask image
      docker_container:
        name: flask
        image: hargovind04/checkup_ease_backend:latest
        state: started
        restart: yes
        restart_policy : always
        env: 
          APP_NAME: "app"
          APP_ENV: "production"
          MONGODB_DATABASE: "flaskdb"
          MONGODB_HOSTNAME: "mongodb"
        links:
          - "mongodb:mongodb"
        exposed_ports:
          - "8080"

- name: Pull and Run Custom FLask Image
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Pull react image
      docker_image:
        name: hargovind04/checkup_ease_frontend:latest
        source: pull

    - name: Running react image
      docker_container:
        name: react
        image: hargovind04/checkup_ease_frontend:latest
        state: started
        restart: yes
        restart_policy : always
        links: 
          - "flask:flask"
        exposed_ports:
          - "3000"        

- name: Pull and Run Custom Nginx Image
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Pull nginx image
      docker_image:
        name: hargovind04/checkup_ease_nginx:latest
        source: pull

    - name: Running nginx image
      docker_container:
        name: nginx
        image: hargovind04/checkup_ease_nginx:latest
        state: started
        restart: yes
        restart_policy : always
        links: 
          - "react:react"
        ports:
          - "80:80"
